### ISSUE TITLE
Tocar música

### ISSUE THREAD

**Issue by NicolasM3** [oGabrielArruda/monitoria-bot#1]
Você poderia colocar  funcionalidade de tocar música neste bot. Ou adicionar um bot de música no servidor.

**Comment by oGabrielArruda** [comment]
mó preguiça parceiro

**Comment by NicolasM3** [comment]
https://tecnoblog.net/353923/6-bots-de-musica-para-usar-no-discord/

**Comment by Nouani** [comment]
Apoio
